// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoListProject.Models
{
    public partial class List
    {
        public List()
        {
            Todos = new HashSet<Todo>();
        }

        public int ListId { get; set; }
        public string ListName { get; set; }

        public virtual ICollection<Todo> Todos { get; set; }
    }
}