// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoListProject.Models
{
    public partial class Todo
    {
        public int TodoId { get; set; }
        public int? ListId { get; set; }
        public string TodoName { get; set; }
        public DateTime? FinishDate { get; set; }
    }
}